name: amazingplaces
favicon: null
layout_spectrum: 0.9213623348623514
typography_spectrum: 0.20214775181375444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8364859900902957
  lightness: 0.9011312886141241
  saturation: 0.45466037397272885
  rhythmicContrast: 0.0867760528344661
purpose: []
